var g=(e,t,r)=>{if(!t.has(e))throw TypeError("Cannot "+r)};var p=(e,t,r)=>(g(e,t,"read from private field"),r?r.call(e):t.get(e)),m=(e,t,r)=>{if(t.has(e))throw TypeError("Cannot add the same private member more than once");t instanceof WeakSet?t.add(e):t.set(e,r)},y=(e,t,r,a)=>(g(e,t,"write to private field"),a?a.call(e,r):t.set(e,r),r);var E=(e,t,r)=>(g(e,t,"access private method"),r);import{a as R,S as U,i as w}from"./assets/vendor-51b8eb1f.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const x="https://pixabay.com/api/";var l,u,I;class Y{constructor(t){m(this,u);m(this,l,void 0);y(this,l,R.create({baseURL:x,params:{key:t}}))}searchImages(t){return E(this,u,I).call(this,"",t)}}l=new WeakMap,u=new WeakSet,I=async function(t,r){return(await p(this,l).get(t,{params:r})).data};const C="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAENSURBVHgBrZVhDoIwDIUrgfDXm+hRvBFwEr0BXsXjsJnMFVkYsvUV4SWL6Nr3MWgrUUbW2sYY6zSLY3M+Zc7cOWr9evqvL5J18av1OVRVVUdI4c6HwTxIKY5FJ/nbXA3ZYw4hR5hnIZK5MeaKDFMxC8jX3PapRPTi5lJOQWzPewHQpgz49xxkPrmcKwJyEGQe55UEVNdV64P5cmwm1tSEHe+hfAj4hUwAlTmrIKWKglzqGkl1gmg2hVmjnj0QEJuHxxK/EwiRqkGqFqmE433YaJpSFBttDnrfUxACSsWw1+LmJMhWrcyDjoBkzY+AQPM9EMl81QdhLJxOrvGfZ1L96bvblvExaj4JXtJj+QAn5UUxjHYd+gAAAABJRU5ErkJggg==";function O(e){return e.map(t=>j(t)).join("")}function j({webformatURL:e,largeImageURL:t,tags:r,likes:a,views:s,comments:o,downloads:n}){let A=`<li class="gallery-item">
                <a class="gallery-image-link" href="${t}">
                    <img 
                        class="gallery-image" 
                        src="${e}" 
                        alt="${r}" 
                    />
                </a>
                <ul class="gallery-item-stats">`;for(const[M,B]of Object.entries({likes:a,views:s,comments:o,downloads:n}))A+=`<li class="gallery-item-stats-item">
                                <p class="gallery-item-stats-label">${M}</p>
                                <p class="gallery-item-stats-value">${B}</p>
                              </li>`;return A+="</ul></li>"}const q="25546966-f3ef2260a4c78c9f4c7cc9e45",J={image_type:"photo",orientation:"horizontal",safesearch:!0},L=15,S=1,Q=new Y(q),T=new U(".gallery a",{captionsData:"alt",captionDelay:250,captionsPosition:"bottom"}),P=document.querySelector("#search-form"),v=document.querySelector(".gallery"),F=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");let i={page:S,per_page:L},h,c=null;function G(e){v.innerHTML="",i.page=S,h=e,c=null}function H(){const t=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({behavior:"smooth",top:(t.height+48)*2})}f.addEventListener("click",e=>{b()});P.addEventListener("submit",e=>{e.preventDefault();const t=e.currentTarget.searchField.value.trim();if(t===""){d("You have to write something!");return}t!==h&&G(t),b()});async function b(){D(),X();let e;try{e=await Q.searchImages({q:h,...i,...J})}catch(t){d(t.message)}finally{_(),P.reset()}if(e.totalHits===0){d("Sorry, there are no images matching your search query. Please try again!");return}v.insertAdjacentHTML("beforeend",O(e.hits)),T.refresh(),i.page!==1&&H(),c===null&&(c=Math.ceil(e.totalHits/L)),++i.page>c?V("We're sorry, but you've reached the end of search results."):k()}function d(e){w.error({title:"Error",message:e,iconUrl:C,position:"topRight",titleColor:"#FFF",messageColor:"#FFF",backgroundColor:"#EF4040",theme:"dark",progressBar:!1,close:!1})}function V(e){w.info({title:"Info",message:e,position:"topRight",titleColor:"#FFF",messageColor:"#FFF",theme:"dark",progressBar:!1,close:!1})}function X(){F.classList.remove("hidden")}function _(){F.classList.add("hidden")}function k(){f.classList.remove("hidden")}function D(){f.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
